function info = resamp_periodic_step_visualize_frame(state, params, step, varargin)
%RESAMP_PERIODIC_STEP_VISUALIZE_FRAME Visualization for the periodic-step resampling demo.
%
% Compared with resamp_pool_visualize_frame, this figure emphasizes the
% staircase interface and the weighted flow field generated by the periodic
% step/shear initialization.  It remains fully periodic and uses no wall or
% solid mask.

if nargin < 3
    error('Usage: info = resamp_periodic_step_visualize_frame(state, params, step, ...)');
end
opts = parse_options(params, varargin{:});
active = resamp_active_mask(state);
G = resamp_deposit_weighted_to_grid(state.x, state.v, state.m, params, ...
    'periodicX', true, 'periodicY', true, 'activeMask', active);
md = resamp_population_mass_diagnostics(state, params, 'periodicX', true, 'periodicY', true);

Nx = params.Nx;
Ny = params.Ny;
dx = params.Lx / Nx;
dy = params.Ly / Ny;
xc = ((0:Nx-1) + 0.5) * dx;
yc = ((0:Ny-1) + 0.5) * dy;
[X, Y] = ndgrid(xc, yc); %#ok<ASGLU>

gamma = getf(params, 'gamma', max(mean(G.N(:), 'omitnan'), eps));
m0 = getf(params, 'resampParticleMass', getf(params, 'particleMass', 1.0));
Mtarget = getf(params, 'resampTargetCellMass', gamma * m0);
Nmin = getf(params, 'resampNMin', ceil(0.5 * gamma));
Nmax = getf(params, 'resampNMax', ceil(1.5 * gamma));

Nrel = double(G.N) / max(gamma, eps) - 1.0;
Mrel = double(G.M) / max(Mtarget, eps) - 1.0;
speed = sqrt(G.Ux.^2 + G.Uy.^2);
omega = periodic_vorticity(G.Ux, G.Uy, dx, dy);
[classMap, classLabels] = population_class_map(G.N, Nmin, Nmax, opts.insertDiag);
[ifaceX, ifaceY] = step_interface_polyline(params);

fig = figure;%(opts.figureId); %#ok<NASGU>
clf;
set(gcf, 'Name', opts.figureName, 'Color', 'w');
method = getf(params, 'method', 'resamp');
forceDiag = getf(opts.stepDiag, 'kolmogorovForce', struct());
forceMode = getf(forceDiag, 'mode', getf(params, 'forceMode', 'none'));
forceAmp = getf(forceDiag, 'amplitude', getf(params, 'kolmogorovForceAmplitude', NaN));
forceKick = getf(forceDiag, 'kickRms', NaN);
sgtitle(sprintf(['periodic step %s step %d, t=%.4g | Nact=%d/%d free=%d insertedNow=%s cum=%s last=%s ', ...
                 '| N[min,max]=[%g,%g] MrelRMS=%.2e mRelStd=%.2e kBT=%.3g thermAfter=%.3g ', ...
                 '| force=%s A=%.3g kickRMS=%.2e'], ...
    char(string(method)), step, step * getf(params,'dt',0), ...
    md.NpActive, md.Ncapacity, md.Nfree, ...
    format_scalar(getf(opts.insertDiag,'nInsertedParticles',NaN)), ...
    format_scalar(getf(opts.insertDiag,'nInsertedParticlesCumulative',NaN)), ...
    format_scalar(getf(opts.insertDiag,'lastInsertionStep',NaN)), ...
    md.NMin, md.NMax, md.MRelRms, md.mParticleRelStd, md.kBTWeighted, ...
    getf(getf(opts.stepDiag,'thermostatAfterRemap',struct()), 'meanKBTAfter', NaN), ...
    char(string(forceMode)), forceAmp, forceKick));

subplot(2,3,1);
plot_particles_by_mass(state, active, params, opts.maxParticles, m0);
hold on; plot(ifaceX, ifaceY, 'k-', 'LineWidth', 1.5); hold off;
title('active particles colored by m_p + initial step');

subplot(2,3,2);
imagesc(xc, yc, Nrel'); axis xy equal tight; colorbar; hold on; plot(ifaceX, ifaceY, 'k-', 'LineWidth', 1.2); hold off;
title('population N/\gamma - 1'); xlabel('x'); ylabel('y');
set_symmetric_clim(gca, Nrel, getf(params,'visualPopulationRelCLim',NaN));

subplot(2,3,3);
imagesc(xc, yc, Mrel'); axis xy equal tight; colorbar; hold on; plot(ifaceX, ifaceY, 'k-', 'LineWidth', 1.2); hold off;
title('cell mass M/M_{target} - 1'); xlabel('x'); ylabel('y');
set_symmetric_clim(gca, Mrel, getf(params,'visualMassRelCLim',NaN));

subplot(2,3,4);
imagesc(xc, yc, G.Ux'); axis xy equal tight; hold on; colorbar;
strideX = opts.quiverStrideX;
strideY = opts.quiverStrideY;
ix = 1:strideX:Nx;
iy = 1:strideY:Ny;
quiver(X(ix,iy), Y(ix,iy), G.Ux(ix,iy), G.Uy(ix,iy), getf(params,'visualQuiverScale',1.2), 'k');
plot(ifaceX, ifaceY, 'w-', 'LineWidth', 1.2); hold off;
title('weighted U_x + quiver'); xlabel('x'); ylabel('y');
set_symmetric_clim(gca, G.Ux, getf(params,'visualUxCLim',NaN));

subplot(2,3,5);
imagesc(xc, yc, omega'); axis xy equal tight; colorbar; hold on; plot(ifaceX, ifaceY, 'k-', 'LineWidth', 1.2); hold off;
title('\omega = \partial_x u_y - \partial_y u_x'); xlabel('x'); ylabel('y');
set_symmetric_clim(gca, omega, getf(params,'visualOmegaCLim',NaN));

subplot(2,3,6);
imagesc(xc, yc, classMap'); axis xy equal tight; hold on; plot(ifaceX, ifaceY, 'k-', 'LineWidth', 1.2); hold off;
caxis([-2 2]);
cbClass = colorbar;
set(cbClass, 'Ticks', -2:2, 'TickLabels', {'empty','poor','ok','over','insert'});
title(sprintf('population class: %s', classLabels)); xlabel('x'); ylabel('y');

info = struct();
info.G = G;
info.massDiagnostics = md;
info.omega = omega;
info.classMap = classMap;
info.Nrel = Nrel;
info.Mrel = Mrel;
info.speed = speed;
info.interfaceX = ifaceX;
info.interfaceY = ifaceY;

drawnow limitrate;
if opts.saveFrame
    if ~exist(opts.frameDir, 'dir')
        mkdir(opts.frameDir);
    end
    exportgraphics(gcf, fullfile(opts.frameDir, sprintf('%s_%06d.png', opts.framePrefix, step)), 'Resolution', 150);
end
end

function opts = parse_options(params, varargin)
opts = struct();
opts.insertDiag = struct();
opts.remapDiag = struct(); %#ok<STRNU>
opts.stepDiag = struct();
opts.figureId = getf(params, 'visualFigureId', 640);
opts.figureName = 'Weighted resampling periodic step';
opts.saveFrame = false;
opts.frameDir = fullfile('runs','resamp_periodic_step_visual','frames');
opts.framePrefix = 'resamp_periodic_step';
opts.maxParticles = getf(params, 'visualMaxParticles', 15000);
opts.quiverStrideX = max(1, round(params.Nx / 24));
opts.quiverStrideY = max(1, round(params.Ny / 16));
for k = 1:2:numel(varargin)
    key = lower(string(varargin{k}));
    val = varargin{k+1};
    switch key
        case 'insertdiag'
            opts.insertDiag = val;
        case 'remapdiag'
            opts.remapDiag = val;
        case 'stepdiag'
            opts.stepDiag = val;
        case 'figureid'
            opts.figureId = val;
        case 'figurename'
            opts.figureName = char(string(val));
        case {'saveframe','saveframes'}
            opts.saveFrame = logical(val);
        case 'framedir'
            opts.frameDir = char(string(val));
        case 'frameprefix'
            opts.framePrefix = char(string(val));
        case {'maxparticles','visualmaxparticles'}
            opts.maxParticles = val;
        case 'quiverstridex'
            opts.quiverStrideX = val;
        case 'quiverstridey'
            opts.quiverStrideY = val;
        otherwise
            error('Unknown visualization option: %s', string(key));
    end
end
end

function [xLine, yLine] = step_interface_polyline(params)
Lx = params.Lx;
Ly = params.Ly;
xs = getf(params, 'periodicStepXFraction', 0.35) * Lx;
yLow = getf(params, 'periodicStepYLowFraction', 0.35) * Ly;
yHigh = getf(params, 'periodicStepYHighFraction', 0.65) * Ly;
xLine = [0, xs, xs, Lx];
yLine = [yLow, yLow, yHigh, yHigh];
end

function plot_particles_by_mass(state, active, params, maxParticles, m0)
ids = find(active);
if isempty(ids)
    plot(nan, nan, '.'); axis equal tight;
    return;
end
if numel(ids) > maxParticles
    ids = ids(round(linspace(1, numel(ids), maxParticles)));
end
scatter(state.x(ids,1), state.x(ids,2), 4, state.m(ids), 'filled');
axis equal tight; xlim([0 params.Lx]); ylim([0 params.Ly]); colorbar;
if isfinite(m0) && m0 > 0
    caxis([0.5*m0, 1.5*m0]);
end
xlabel('x'); ylabel('y');
end

function omega = periodic_vorticity(Ux, Uy, dx, dy)
dUyDx = (circshift(Uy, [-1,0]) - circshift(Uy, [1,0])) / (2*dx);
dUxDy = (circshift(Ux, [0,-1]) - circshift(Ux, [0,1])) / (2*dy);
omega = dUyDx - dUxDy;
end

function [classMap, labels] = population_class_map(N, Nmin, Nmax, insertDiag)
classMap = zeros(size(N));
classMap(N == 0) = -2;
classMap(N > 0 & N < Nmin) = -1;
classMap(N > Nmax) = 1;
if isstruct(insertDiag) && isfield(insertDiag, 'insertedPerCellGrid') && ~isempty(insertDiag.insertedPerCellGrid)
    ins = insertDiag.insertedPerCellGrid;
    if isequal(size(ins), size(classMap))
        classMap(ins > 0) = 2;
    end
end
labels = '-2 empty, -1 poor, 0 ok, 1 over, 2 inserted';
end

function set_symmetric_clim(ax, A, forced)
if nargin >= 3 && isnumeric(forced) && isscalar(forced) && isfinite(forced) && forced > 0
    clim(ax, [-forced forced]);
    return;
end
mx = max(abs(A(:)), [], 'omitnan');
if ~isfinite(mx) || mx <= 0
    mx = 1;
end
clim(ax, [-mx mx]);
end

function s = format_scalar(v)
if isempty(v) || ~isfinite(v)
    s = 'n/a';
elseif abs(v - round(v)) < 10*eps(max(1, abs(v)))
    s = sprintf('%d', round(v));
else
    s = sprintf('%.4g', v);
end
end

function value = getf(s, name, defaultValue)
if isstruct(s) && isfield(s, name) && ~isempty(s.(name))
    value = s.(name);
else
    value = defaultValue;
end
end
