function out = run_resamp_poiseuille_wallvp_mass_regularization_once(varargin)
%RUN_RESAMP_POISEUILLE_WALLVP_MASS_REGULARIZATION_ONCE One-shot mass regularization test.
%
% This wrapper reproduces the q6_resampled_wallvp Poiseuille validation run
% and applies the mass renormalization exactly once at step 3000.  All other
% physical/numerical defaults are inherited from
% run_resamp_poiseuille_wallvp_validation so that the output can be compared
% directly with the previous q6/resampling wallVP run.

args = [{ ...
    'cases', {'q6_resampled_wallvp'}, ...
    'steps', 5000, ...
    'sampleEvery', 50, ...
    'summaryEvery', 100, ...
    'visualEvery', 0, ...
    'saveFinalFigures', true, ...
    'massRegularizationEnable', true, ...
    'massRegularizationStep', 3000, ...
    'massRegularizationStrength', 1.0, ...
    'massRegularizationTriggerMode', 'always', ...
    'massRegularizationPreserveEnergy', true, ...
    'massRegularizationMinFactor', 0.25, ...
    'massRegularizationMaxFactor', 4.0, ...
    'outputRoot', fullfile('runs','resamp_poiseuille_wallvp_mass_regularization_once') ...
    }, varargin];

out = run_resamp_poiseuille_wallvp_validation(args{:});
end
