function out = run_resamp_population_heterogeneity_demo(varargin)
%RUN_RESAMP_POPULATION_HETEROGENEITY_DEMO Visual TG test with distributed population heterogeneity.
%
% This runner is an intermediate designed test between the two-pocket
% recycling demo and more physical flows.  It creates a spatially distributed
% heterogeneous initial population field, then activates the closed-loop
% weighted recycling method.
%
% Example:
%   out = run_resamp_population_heterogeneity_demo( ...
%       'PopulationHeterogeneityStd',4, 'steps',300);

defaultArgs = { ...
    'method','weighted_q6', ...
    'steps',300, ...
    'visualEvery',5, ...
    'summaryEvery',25, ...
    'initialDepletion','heterogeneous_population', ...
    'PopulationHeterogeneityStd',4, ...
    'NMin',14, ...
    'NTarget',20, ...
    'NMax',26, ...
    'ExtractEvery',1, ...
    'InsertEvery',1, ...
    'ExtractSelectionMode','closest_to_cell_mean', ...
    'RemapMassSafetyEnable',true, ...
    'RemapMassSafetyMode','uniform_mass_velocity_shift', ...
    'RemapMassSafetyMinFactor',0.25, ...
    'RemapMassSafetyMaxFactor',4.0, ...
    'ThermostatAfterRemap',true, ...
    'ThermostatStrength',0.25, ...
    'ThermostatTargetKBT',0.01, ...
    'rngSeed',12345, ...
    'outputDir',fullfile('runs','resamp_population_heterogeneity_demo'), ...
    'frameDir',fullfile('runs','resamp_population_heterogeneity_demo','frames'), ...
    'framePrefix','resamp_heterogeneous_population'};

out = run_resamp_pool_insertion_visual_demo(defaultArgs{:}, varargin{:});
end
