function out = run_resamp_recycling_pockets_demo(varargin)
%RUN_RESAMP_RECYCLING_POCKETS_DEMO Designed test for extraction + insertion recycling.
%
% This is not a gentle physics validation.  It intentionally creates, at
% t=0, one empty patch and one overpopulated patch with the same particle
% count moved from the former to the latter.  The first population-edit pass
% must therefore extract from the rich patch, insert into the empty patch,
% and then let the conservative remap restore cell mass/momentum.
%
% Example:
%   out = run_resamp_recycling_pockets_demo('steps',20,'visualEvery',1);

out = run_resamp_pool_insertion_visual_demo( ...
    'method','weighted_q6', ...
    'steps',20, ...
    'visualEvery',1, ...
    'summaryEvery',1, ...
    'initialDepletion','paired_pockets', ...
    'depletionPatchSize',[6 6], ...
    'NMin',10, ...
    'NTarget',20, ...
    'NMax',30, ...
    'ExtractEvery',1, ...
    'InsertEvery',1, ...
    'ExtractSelectionMode','closest_to_cell_mean', ...
    'ThermostatAfterRemap',true, ...
    'ThermostatStrength',0.25, ...
    'ThermostatTargetKBT',0.01, ...
    'outputDir',fullfile('runs','resamp_recycling_pockets_demo'), ...
    'frameDir',fullfile('runs','resamp_recycling_pockets_demo','frames'), ...
    varargin{:});
end
